### ISSUE TITLE
BP-BGT-WOLDMAP installer: Small Worldmap 4900x3500 and Drizzt Saga mod

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BP-BGT-Worldmap#10]
With the last version of worldmap (10.2.6), it is no more possible to install the `Small Worldmap 4900x3500` version with Drizzt Saga installed; Without prompting, the installer chooses the `Large Worldmap 8000x6300`.

However, and for Drizzt Saga, the auto-installation of the Large Worldmap is not mandatory as the `Small Worldmap 4900x3500` has the needed area in the top left corner...

**Comment by Roberciiik** [comment]
Hi TotoR,

I verified the issue on the following configurations:
- `BGT`+`DS`+`Worldmap`: Small worldmap installed correctly,
- `BGEE`+`DS`+`Worldmap`: Small worldmap installed correctly,
- `BGEE`+`SoD`+`DS`+`Worldmap`: Small worldmap installed correctly,
- `DS on BG:SoD`+`EET`+`Worldmap`: Small worldmap installed correctly.

Could you specify what is your configuration (WeiDU.log?). If any other mod was installed that has areas on the northern part, it will automatically choose Large worldmap version.

**Comment by TotoR115** [comment]
I have done some tests, but I am unable to reproduce the issue with my actual config and I don't remember what was in it (it was some time ago)...

The issue might be linked to mods that are not configured with Worldmap and use BGT area.tbl for both. 

This issue can be closed I think.

**Comment by Roberciiik** [comment]
Feel free to reopen when you find reproduction steps. Thanks!
