### ISSUE TITLE
Request - fft map icon for YS0390.are

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BP-BGT-Worldmap#24]
Fishing for trouble does not use dedicated icon for the YS0390.are (Government District Westside)

The existing tbl could be updated with designated icon from new bpbgtmap.bam

**Comment by weigo87** [comment]
The Icon number is still 182. We didn't change the bam number.

**Comment by Roberciiik** [comment]
I will patch fft files (that are already in BP-BGT-Worldmap) the same way as I have done for Lava's mods. However, the best solution is to update the fft mod too!

**Comment by TotoR115** [comment]
> However, the best solution is to update the fft mod too!

I will make a PR for fft

**Comment by Roberciiik** [comment]
Correct, that's why I said: 
> I will patch fft files (that are already in BP-BGT-Worldmap)

**Comment by TotoR115** [comment]
PR is done for FFT (https://github.com/InfinityMods/FishingForTrouble/pull/7#issue-1571617589)

FWIW, the `fft_areas.tbl ` need also to be updated for YS0370 as icon is 98 (https://github.com/InfinityMods/FishingForTrouble/blob/4e2996caa0b71bad10b21b6c1dc6956dd667d385/FishingForTrouble/lib/patch_worldmap.tpa#L15)
