### ISSUE TITLE
Map is unusable for bg1ee (and probable for bg2ee) not eet.

### ISSUE THREAD

**Issue by abalabokhin** [SpellholdStudios/BP-BGT-Worldmap#26]
I am not sure should this mod work with bg1ee and bg2ee (not eet), but it would be nice if it can. Right now, after installing it on the bg1ee, all the coordinates are wrong, see the attached screenshot.

![Screenshot_20230128_175944](https://user-images.githubusercontent.com/754271/215295021-8c1009f7-58f4-46d0-8044-ece5e4f2cbc4.png)

**Comment by Roberciiik** [comment]
It is working with BG:EE. However, you need to start a new game for correct worldmap displaying. As you can see, game still shows the old icons from the paper worldmap of BG1.
![Baldr035](https://user-images.githubusercontent.com/26695895/215320595-9a3c5a32-dd34-4bea-9c70-1eee095d999a.png)

**Comment by abalabokhin** [comment]
Thank you, my bad.

**Comment by abalabokhin** [comment]
After checking in debug mode, there are still some troubles if install on bg1ee. Some icons are missing, some icons don't have names. (The map is in Russian, but I think is it the same in English).
![0002](https://user-images.githubusercontent.com/754271/215335778-53155ef1-e854-4c10-a267-25a05da3e5f3.jpg)

**Comment by Roberciiik** [comment]
Can you point out what icons are missing? Here is an original BG:EE map and the Worldmap screens shots. It looks the same for me. Also, the "missing" names are intentionally set to empty strings, the same way as in the original BG1 games.

![63ee8dde10c79b0c3bf1980b3c065d](https://user-images.githubusercontent.com/26695895/215867707-f73fb3bf-2652-4198-87c9-cf7ad8e4d6a1.jpg)
![Baldr035](https://user-images.githubusercontent.com/26695895/215867725-27cb0f23-0448-4fb8-b35f-bafc6a8831d0.png)
![Baldr036](https://user-images.githubusercontent.com/26695895/215867742-a3b7b6bf-e7a4-4d89-b8ce-ffcd1ac4b4d8.png)
