### ISSUE TITLE
bp-bgt-worldmap:1 skipped on EET

### ISSUE THREAD

**Issue by 4udr4n** [SpellholdStudios/BP-BGT-Worldmap#3]
bp-bgt-worldmap:1:Use new Worldmap for Throne of Bhaal as well was skipped:
"This component is not available for this game."

Looks like this should be available for EET. Please advise if not.
[WeiDU.log](https://github.com/SpellholdStudios/BP-BGT-Worldmap/files/4551092/WeiDU.log)
[SETUP-BP-BGT-WORLDMAP.txt](https://github.com/SpellholdStudios/BP-BGT-Worldmap/files/4551093/SETUP-BP-BGT-WORLDMAP.txt)

**Comment by GraionDilach** [comment]
I know this is a late one, but EET always loads the "SoA" worldmap for ToB. The component is not needed, because the ToB worldmap files are never used.
