### ISSUE TITLE
Is it possible to add iwd1-eet and iwd2-eet icons to the mod?

### ISSUE THREAD

**Issue by abalabokhin** [SpellholdStudios/BP-BGT-Worldmap#39]
It is not an issue, but rather a feature request.

There are two mods that works only with EET: iwd1-eet and iwd2-eet (https://github.com/11jo/IWD1_EET, https://github.com/11jo/IWD2_EET) made by Tipun from https://arcanecoast.ru/. They add the whole iwd1, iwd2 stories to EET. After installing these two mods another mod for Worldmap (https://github.com/11jo/Worldmap_IWD_EET) should be installed to add icons and locations for IWD content.

Is it possible to add all icons and locations from Worldmap_IWD_EET to this mod, so there is no need in Worldmap_IWD_EET mod at all? Or maybe it is already done to some extent...
Tipun said that he had sent all the necessary information before to somebody, but he is not sure, what is the current state...

**Comment by weigo87** [comment]
I have just made contact with Tipun. We talked about this topic last year. Here is the message:

> Hi Tipun, your IWD1&2 EET is excellent. I have a question for you guys. After discovering the Github version, I would like to get a pull request ready so that you can support the BP-BGT worldmap direct?
The whole thing for IWD1 and 2. So we would not need a Worldmap_IWD_EET mod anymore. 

The week after next I would have vacation, then I could finish the code.

**Comment by weigo87** [comment]
The code is ready, but Tipun seems to be busy in real life. I have not received any response yet. I rewrote the whole _worldmap.tph code and used newer versions of some functions. I will finish the files this weekend and upload a pull request to github.

**Comment by abalabokhin** [comment]
I believe by this moment the pull requests are accepted for iwd1/iwd2 repositories, so I am closing the issue. Thank you again for your work. 

PS At some point we will test it all together. Did I understand it properly that now you can install iwd1-eet, iwd2-eet and worldmap (what version?)mods, and all icons should be on the proper positions?

**Comment by weigo87** [comment]
I cannot say exactly whether all the icons are in the right place. If a position needs to be changed, open the Area-Bp-Bgt.tbl in the worldmap folder of the mod and change the coordinates.
From version 11 of the Bp-Bgt worldmap https://github.com/SpellholdStudios/BP-BGT-Worldmap it is compatible with IWD-EET
