### ISSUE TITLE
Worldmap Readme Icon/Image Links Broken

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/BP-BGT-Worldmap#4]
Greetings!

The links to the icons/pictures in this mod's readme are broken, and these images seem to be the only official way to distinguish one type of install from another.  May we get this fixed?

Thankee!

**Comment by GwendolyneFreddy** [comment]
Thanks for reporting. The issue was due to the mod top folder change.

Fixed.

**Comment by Endarire** [comment]
Thankee again for addressing this.  I apologize.  Perhaps I clicked the wrong file.
