### ISSUE TITLE
Incorrent label for Candlekeep if installed on BG1EE

### ISSUE THREAD

**Issue by abalabokhin** [SpellholdStudios/BP-BGT-Worldmap#41]
If this mod installed on BG1EE (didn't check with EET), Candlekeep label has both "Traveling Hours" and "Destination Unreachable" (can be checked immediately after the new game), see attached (in Russian). Probably "Destination Unreachable" should not be there.
![01](https://user-images.githubusercontent.com/754271/218586100-56e61384-e433-45b8-8efd-831f2497850f.jpg)

Added, it is the same in English version:
![baldr005](https://user-images.githubusercontent.com/754271/218725311-b89c2e4f-7930-43dc-ad43-d0fd1d1a66ba.jpg)

**Comment by Roberciiik** [comment]
Used the same approach as in EET. Should be fine now.
