### ISSUE TITLE
Can't install Worldmap 12 [Tileconv on Linux]

### ISSUE THREAD

**Issue by jcvignoli** [SpellholdStudios/BP-BGT-Worldmap#66]
I'm getting the following error when installing worldmap 12 on linux:

`Huge worldmap 8000x6300 is required and will be installed
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
FAILURE:
ERROR: tileconv not found: ""
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.`

I'm installing the French version, but the English results in same error. With version 11 I can install flawlessly.

Weidu log is attached.
[setup-bp-bgt-worldmap.zip](https://github.com/SpellholdStudios/BP-BGT-Worldmap/files/13328191/setup-bp-bgt-worldmap.zip)

I'm using infinity_ui, could it be related?

**Comment by Roberciiik** [comment]
Version 12 introduced a new tool for tile conversion. I'm not sure if it supports Linux. Will check, In the meantime I suggest to use v11. Should work with all your modification that you are using.

**Comment by jcvignoli** [comment]
I confim it works with v11. Will wait to use v12, the new icons you added will fit perfectly with my new mods.

thanks,

**Comment by Roberciiik** [comment]
Ok so from the code I can see that Linux version is attached. Could you try to edit lib.tpa lines from:
```
	LAF HANDLE_TILECONV
	  STR_VAR
		input_path = EVAL "%path%"
		output_path	  = EVAL "bp-bgt-worldmap/language"
	END
```

to 
```
	LAF HANDLE_TILECONV
	  STR_VAR
		input_path = EVAL "%path%"
                tileconv_path = "bp-bgt-worldmap/tools/tileconv/linux/x86_64"
		output_path	  = EVAL "bp-bgt-worldmap/language"
	END
```

or play with this variable a bit to match proper path to the binary.

**Comment by jcvignoli** [comment]
I did as you recommended, but I get a new error:
`Huge worldmap 8000x6300 is required and will be installed
Copying and patching 1 file ...
Creating 1 directory
/bin/sh: 1: bp-bgt-worldmap/tools/tileconv/linux/x86_64: Permission denied
Creating 1 directory
/bin/sh: 1: bp-bgt-worldmap/tools/tileconv/linux/x86_64: Permission denied
Creating 1 directory
/bin/sh: 1: bp-bgt-worldmap/tools/tileconv/linux/x86_64: Permission denied
Copying 1 file ...
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Worldmap for Baldur's Gate - including colored Baldur's Gate map icons], rolling back to previous state
Will uninstall  32 files for [bp-bgt-worldmap/setup-bp-bgt-worldmap.tp2] component 0.
Uninstalled     32 files for [bp-bgt-worldmap/setup-bp-bgt-worldmap.tp2] component 0.
ERROR: Unix.Unix_error(Unix.ENOENT, "stat", "bp-bgt-worldmap/language/english/mbc/worldmap_large.mos")
Please make a backup of the file: setup-bp-bgt-worldmap.debug and look for support at: www.shsforums.net/forum/401-worldmap/
`
I tried to chmod 777 tileconv, no luck. If I change the "tileconv_path", it says not found, so it is actually found but can't be executed.

**Comment by Roberciiik** [comment]
Are you able to run tileconv tool from the console? By yourself without the modification?

**Comment by jcvignoli** [comment]
Absolutely, I can run it (as long as I make it executable)

**Comment by Roberciiik** [comment]
Unfortunately, I don't have a Linux to resolve this issue now. I will ask for some help on the forum.

**Comment by jcvignoli** [comment]
It may help to know that Sirines Call and TDDz include tileconv too. I could install both mods, which apparently have the same needs as worldmap.

**Comment by Roberciiik** [comment]
I copied binaries structure from Sirines' Call mod. Could you verify it using this branch:
https://github.com/Roberciiik/BP-BGT-Worldmap/archive/refs/heads/tileconv-linux.zip

Let me know if this is helpful. I can try with older version of the a7tools script.

**Comment by jcvignoli** [comment]
I have to run extra tests with proper vanilla BG install, but so far it's good.
But now I get an extra question that put an ends to automatized installation:

> Which size of the worldmap do you want?
> 
> 1. Large Worldmap 4900x3500
> 2. Huge Worldmap 8000x6300

Is there a way to bypass the question? I didn't get such question previously.

**Comment by Roberciiik** [comment]
It can detect automatically that you need a huge version of the map if you have installed some mods that require distant regions. Then the question is not showing up.

**Comment by jcvignoli** [comment]
Correct, I installed a fully modded version, and it didn't ask the question.
I also confirm the latest version of worldmap installed flawlessly, thanks!
I however noticed a small glitch: the area map is not centered, see the screenshot (can't remember if with Worlmap 11 it 
![Screenshot from 2023-11-15 07-23-03](https://github.com/SpellholdStudios/BP-BGT-Worldmap/assets/63559091/06dcd243-920d-4ec0-9728-a713f467cd29)

**Comment by Roberciiik** [comment]
Great to hear that installtion goes fine. However, I don't think Worldmap touches this view. I can see that you are using some UI mod(s). Maybe it is causing this issue from the screenshot.

**Comment by jcvignoli** [comment]
Very good, I'll try to investigate further what mod may be responsible for the issue.
Thanks again for your help, can't wait for playing my moded game and benefit from the very extensive worldmap I now get.

**Comment by Roberciiik** [comment]
It might be worth to check if this is reproducible on clean installation only with Worldmap. If not, it is probably some compatibility issues with other UI mod. Thanks for the help with investigation.

**Comment by jcvignoli** [comment]
I've just tested on a vanilla BGII (so not the very same map, but a BGII map), and it works out.
I could test on a vanilla BGT (so BGI + EET) if you think it's worth it.

**Comment by Roberciiik** [comment]
Only if you test both scenarios: Worldmap and Worldmap+Your UI mod to see if there is a glitch.

**Comment by jcvignoli** [comment]
I tested both scenarios: one with (BGII EET) dragon ui, one without. The later doesn't have the bug, the former does.
I installed worldmap with dragon ui compatibliity option.
