### ISSUE TITLE
Issue with Drizzt Saga

### ISSUE THREAD

**Issue by jcvignoli** [SpellholdStudios/BP-BGT-Worldmap#70]
Hello,
Small glitch with Drizzt Saga:
![Screenshot from 2023-12-11 22-58-57](https://github.com/SpellholdStudios/BP-BGT-Worldmap/assets/63559091/aa6ea812-2f76-4026-af1e-09cf865b5cac)

My weidus (BGI and BGII) logs 
[weidus.zip](https://github.com/SpellholdStudios/BP-BGT-Worldmap/files/13660429/weidus.zip)
are attached.

It may be related to the fact I started the game with Worldmap 11 installed, and then I made a new install with Worldmap 12 and continued to use the same game, don't know, but maybe worth checking.

**Comment by Roberciiik** [comment]
@jcvignoli 

That's right - this is typical behavior of playing a game save after component reinstallation/uninstallation. 

Closing, as it is not directly related to Worldmap mod. Please feel free to reopen if you find an issue with this modification.

Thanks.
