### ISSUE TITLE
How to edit English text in a worldmap into Chinese? 

### ISSUE THREAD

**Issue by Lzw104522773** [SpellholdStudios/BP-BGT-Worldmap#80]
How to edit English text in a worldmap into Chinese? As shown in the picture, "Baldur's Gate"

![image](https://github.com/SpellholdStudios/BP-BGT-Worldmap/assets/149546927/b4fb2baf-a965-4b78-bda2-bb4229d2d0d4)

**Comment by Roberciiik** [comment]
Hello,
You would have to start with this repo: https://github.com/weigo87/BP-BGT-Worldmap-Source-Files
There is an archive with XCF file to use by Gimp image software. You could play with it to add new layers for a new language. Then you can create the MBC file from PNG. Note I've never edited this file. 😅
Questions?

**Comment by MephistoSatanDevil** [comment]
OK. got it.
I will try

**Comment by MephistoSatanDevil** [comment]
Question:
In project BP-BGT-Worldmap-Source-Files, that XCF file size is 8000x6800, but in project BP-BGT-Worldmap, Large Worldmap is 4900x3500 and Huge Worldmap is 8500x6300.
How should I use the XCF file to output the map images of these two sizes?

**Comment by MephistoSatanDevil** [comment]
> Hello, You would have to start with this repo: https://github.com/weigo87/BP-BGT-Worldmap-Source-Files There is an archive with XCF file to use by Gimp image software. You could play with it to add new layers for a new language. Then you can create the MBC file from PNG. Note I've never edited this file. 😅 Questions?

Question:
In project BP-BGT-Worldmap-Source-Files, that XCF file size is 8000x6800, but in project BP-BGT-Worldmap, Large Worldmap is 4900x3500 and Huge Worldmap is 8500x6300.
How should I use the XCF file to output the map images of these two sizes?

**Comment by Roberciiik** [comment]
> How should I get the images of these two sizes with the XCF file ? How do I crop the original image?Is it correct to crop from the top left?

Answer from wiego:

> I left the left side the same and cut the top, right and bottom sides. I had to make the restrictions for the installation of the mods for the top side. Anything smaller than 1700 prevented the mods from being installed. Made simple, right and bottom is easy to crop as long as there are no mods with coordinates in that area. Top and right is very complicated because of the coordinates. And then you just have to change the coordinates in the worldmap.wmp accordingly.

> In addition, I have been add new layers for chinese and finished it. Should I need to create a new pull request to update the archive file In project BP-BGT-Worldmap-Source-Files,?

You can open a PR to sources or simply share this file by hosting and I will update the sources.

> In project BP-BGT-Worldmap-Source-Files, that XCF file size is 8000x6800, but in project BP-BGT-Worldmap, Large Worldmap is 4900x3500 and Huge Worldmap is 8500x6300 (btw: is it a typo in the worldmap.tra file, is it should be 8000x6800?).

Will check that.

**Comment by MephistoSatanDevil** [comment]
> > How should I get the images of these two sizes with the XCF file ? How do I crop the original image?Is it correct to crop from the top left?
> 
> Answer from wiego:
> 
> ```
> I left the left side the same and cut the top, right and bottom sides. I had to make the restrictions for the installation of the mods for the top side. Anything smaller than 1700 prevented the mods from being installed. Made simple, right and bottom is easy to crop as long as there are no mods with coordinates in that area. Top and right is very complicated because of the coordinates. And then you just have to change the coordinates in the worldmap.wmp accordingly.
> ```
> 
> > In addition, I have been add new layers for chinese and finished it. Should I need to create a new pull request to update the archive file In project BP-BGT-Worldmap-Source-Files,?
> 
> You can open a PR to sources or simply share this file by hosting and I will update the sources.
> 
> > In project BP-BGT-Worldmap-Source-Files, that XCF file size is 8000x6800, but in project BP-BGT-Worldmap, Large Worldmap is 4900x3500 and Huge Worldmap is 8500x6300 (btw: is it a typo in the worldmap.tra file, is it should be 8000x6800?).
> 
> Will check that.

Got it. Thank you.

**Comment by Roberciiik** [comment]
Resolved in #81
